### ISSUE TITLE
Suggestion to fix the problem of "deleting the binaries everytime we want to push to git" 

### ISSUE THREAD

**Issue by alpha-verse** [CoffeeBeforeArch/cpp_crash_course#1]
Hi,

Thanks for these basic and informative videos.

I want to suggest following change in .vscode/settings.json file:

Present:

~~~~
{
  "files.associations": {
    "iostream": "cpp",
    "vector": "cpp",
    "chrono": "cpp"
  }
}

~~~~

Proposed:

~~~~

{
  "files.associations": {
    "iostream": "cpp",
    "vector": "cpp",
    "chrono": "cpp"
  },
 "code-runner.executorMap": {
    "cpp": "cd $dir && g++ *.cpp -o $fileNameWithoutExt.out && ./$fileNameWithoutExt.out"
  }
}

~~~~

Due to .gitignore setting you have, this will help devs to skip the "deleting the binary files" after each code runner execution on Visual Studio code.

Of course this is only applicable to Vs Code users 

Thanks again! for wonderful videos on cpp 20 & rust

**Comment by alpha-verse** [comment]
Following  is even better :

~~~~
{
  "files.associations": {
    "iostream": "cpp",
    "vector": "cpp",
    "chrono": "cpp"
  },
  "code-runner.executorMap": {
    "cpp": "cd $dir && g++ *.cpp -o $fileNameWithoutExt.out && ./$fileNameWithoutExt.out && rm $fileNameWithoutExt.out"
  }
}

~~~~

This will delete the generated binary after the execution completes.

**Comment by CoffeeBeforeArch** [comment]
Thanks for the suggestion!

I think I'd rather just use CMake and have an ignored bin directory than this modification to how code-runner works. From the proposed changes, it looks like it limits the compiler to g++, forces recompilation every time you execute, and only works if you have a single source file (if I understand properly).

--Nick
